blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/ansulx/Medical-Segmentation-Benchmark/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/ansulx/Medical-Segmentation-Benchmark/blob/main/README.md
    about: Check the documentation for usage instructions.
  - name: Examples
    url: https://github.com/ansulx/Medical-Segmentation-Benchmark/blob/main/EXAMPLES.md
    about: Look at examples and tutorials.
